server:
  port: 8084

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

cart:
  ttl-seconds: 604800 # 7 days TTL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET:dev-only-secret-change-me-before-any-real-deployment-32chars+}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
